### ISSUE TITLE
When rendering as image, markers are rendered off their offsets.

### ISSUE THREAD

**Issue by podostro** [vvvv/SVG#212] opened 2016-01-02 17:11 UTC
When rendering to image with `SvgDocument.Draw()` method, the markers on the lines are renderer off their offsets. I'm using nuGet package v2.1.0

Here is an example of the output Image inside a Picturebox:
![image](https://cloud.githubusercontent.com/assets/2327913/12075280/ef71c528-b159-11e5-8ef5-c003936c24a2.png)

Here is the output from `SvgDocument.GetXML()` using the same document

	<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
	<svg x="0" y="0" width="100%" height="100%" overflow="inherit" viewBox="0, 0, 265, 265" preserveAspectRatio="xMidYMid" font-size="0" id="svgmap" xml:space="default" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xml="http://www.w3.org/XML/1998/namespace" version="1.1">
	  <defs id="defsmap" xml:space="default">
		<marker refX="3" refY="2" orient="auto" overflow="hidden" markerWidth="5" markerHeight="5" id="markerArrowLightBlue" xml:space="default">
		  <path d="M0 0 L4 2 L0 4 L1 2 z" id="pathMarkerArrowLightBlue" xml:space="default" style="fill:#ADD8E6;" />
		</marker>
		<marker refX="3" refY="2" orient="auto" overflow="hidden" markerWidth="5" markerHeight="5" id="markerArrowLightCoral" xml:space="default">
		  <path d="M0 0 L4 2 L0 4 L1 2 z" id="pathMarkerArrowLightCoral" xml:space="default" style="fill:#F08080;" />
		</marker>
	  </defs>
	  <g id="gmap" xml:space="default">
		<rect x="80" y="10" width="35" height="35" rx="7" ry="7" stroke="#ADD8E6" id="rectRoomX1Y0" xml:space="default" style="fill:#ADD8E6;" />
		<line x1="78" y1="47" x2="49" y2="76" marker-end="url(#markerArrowLightBlue)" stroke="#ADD8E6" stroke-width="3" id="lineLinkedRoomX0Y1" xml:space="default" />
		<rect x="150" y="10" width="35" height="35" rx="7" ry="7" stroke="#20B2AA" id="rectRoomX2Y0" xml:space="default" style="fill:#20B2AA;" />
		<line x1="167.5" y1="47" x2="167.5" y2="76" marker-end="url(#markerArrowLightBlue)" stroke="#ADD8E6" stroke-width="3" id="lineLinkedRoomX2Y1" xml:space="default" />
		<rect x="10" y="80" width="35" height="35" rx="7" ry="7" stroke="#ADD8E6" id="rectRoomX0Y1" xml:space="default" style="fill:#ADD8E6;" />
		<line x1="47" y1="117" x2="76" y2="146" marker-end="url(#markerArrowLightBlue)" stroke="#ADD8E6" stroke-width="3" id="lineLinkedRoomX1Y2" xml:space="default" />
		<rect x="80" y="80" width="35" height="35" rx="7" ry="7" stroke="#ADD8E6" id="rectRoomX1Y1" xml:space="default" style="fill:#ADD8E6;" />
		<line x1="97.5" y1="78" x2="97.5" y2="49" marker-end="url(#markerArrowLightBlue)" stroke="#ADD8E6" stroke-width="3" id="lineLinkedRoomX1Y0" xml:space="default" />
		<rect x="150" y="80" width="35" height="35" rx="7" ry="7" stroke="#ADD8E6" id="rectRoomX2Y1" xml:space="default" style="fill:#ADD8E6;" />
		<line x1="148" y1="97.5" x2="119" y2="97.5" marker-end="url(#markerArrowLightBlue)" stroke="#ADD8E6" stroke-width="3" id="lineLinkedRoomX1Y1" xml:space="default" />
		<rect x="220" y="80" width="35" height="35" rx="7" ry="7" stroke="#ADD8E6" id="rectRoomX3Y1" xml:space="default" style="fill:#ADD8E6;" />
		<line x1="237.5" y1="117" x2="237.5" y2="146" marker-end="url(#markerArrowLightCoral)" stroke="#F08080" stroke-width="3" id="lineLinkedRoomX3Y2" xml:space="default" />
		<rect x="10" y="150" width="35" height="35" rx="7" ry="7" stroke="#ADD8E6" id="rectRoomX0Y2" xml:space="default" style="fill:#ADD8E6;" />
		<line x1="47" y1="187" x2="76" y2="216" marker-end="url(#markerArrowLightBlue)" stroke="#ADD8E6" stroke-width="3" id="lineLinkedRoomX1Y3" xml:space="default" />
		<rect x="80" y="150" width="35" height="35" rx="7" ry="7" stroke="#ADD8E6" id="rectRoomX1Y2" xml:space="default" style="fill:#ADD8E6;" />
		<line x1="78" y1="167.5" x2="49" y2="167.5" marker-end="url(#markerArrowLightBlue)" stroke="#ADD8E6" stroke-width="3" id="lineLinkedRoomX0Y2" xml:space="default" />
		<rect x="150" y="150" width="35" height="35" rx="7" ry="7" stroke="#ADD8E6" id="rectRoomX2Y2" xml:space="default" style="fill:#ADD8E6;" />
		<line x1="187" y1="148" x2="216" y2="119" marker-end="url(#markerArrowLightBlue)" stroke="#ADD8E6" stroke-width="3" id="lineLinkedRoomX3Y1" xml:space="default" />
		<rect x="220" y="150" width="35" height="35" rx="7" ry="7" stroke="#F08080" id="rectRoomX3Y2" xml:space="default" style="fill:#F08080;" />
		<rect x="80" y="220" width="35" height="35" rx="7" ry="7" stroke="#ADD8E6" id="rectRoomX1Y3" xml:space="default" style="fill:#ADD8E6;" />
		<line x1="117" y1="218" x2="146" y2="189" marker-end="url(#markerArrowLightBlue)" stroke="#ADD8E6" stroke-width="3" id="lineLinkedRoomX2Y2" xml:space="default" />
	  </g>
	</svg>

Here is the same svg as rendered by Chrome (this is the expected result)

![image](https://cloud.githubusercontent.com/assets/2327913/12075309/e43f31bc-b15a-11e5-8336-ecb2a8b79f69.png)

**Comment by podostro** [comment] 2016-01-02 17:12
Here is the same image rendered by Chrome

![image](https://cloud.githubusercontent.com/assets/2327913/12075309/e43f31bc-b15a-11e5-8336-ecb2a8b79f69.png)

**Comment by HeinrichAD** [comment] 2016-01-02 22:50
Hello podostro,

seems like Chome and Firefox works. Internet Explorer does not work. On the other hand
Edge rendered the svg fine. Is the SVG code you added the original code which should be rendered? If not code you upload the original svg file?
Can you tell us which program/ tool you use to generate the svg? Maybe there are some options to set?

**Comment by podostro** [comment] 2016-01-02 23:34
Hi HeinrichAD,

Yes, the code I added in the OP is the same that renders as the attached image in chrome.

I'm not using an external app to create the SVG. I'm creating the `SvgDocument`, and adding all the elements programmatically inside my system.

The first screenshot is from my test app, which takes the created `SvgDocument`, and renders it both to XML using `SvgDocument.GetXML()` and puts into a PictureBox the image returned from `SvgDocument.Draw()`

I don't think I'm missing any svg properties, since the produced XML can actually be rendered in Chrome and Importing it into Inkscape renders ok, too. And as you said, it also render ok both on Firefox and Edge. 

The cause is probably in the innards of the lib's image rendering. But I don't really have much time right now to debug the lib to find it. I'm on a deadline, and the actual output I need is the XML.

Just figured I would post the issue here in case you guys want to improve the lib's rendering to Image. 

If it helps, here is the code from my system that creates and fills the SvgDocument:
Sorry if it doesn't compile, it's just an snip of the code and I had to hide some stuff.

	private void InitializeSVGElements()
	{
		defsElement = new SvgDefinitionList() { ID = "defsMap" };

		groupElement = new SvgGroup() { ID = "gMap" };

		document = new SvgDocument()
		{
			ID = "svgMap",
			ViewBox = new SvgViewBox(0, 0, width, height)
		};

		document.Children.Add(defsElement);
		document.Children.Add(groupElement);
	}

	private SvgMarker MakeArrowMarker(Color color)
	{
		string id = string.Format("markerArrow{0}", color.Name);
		SvgMarker arrowMarker = (SvgMarker)document.GetElementById(id);

		if (arrowMarker == null)
		{
			var arrowPath = new SvgPath()
			{
				ID = string.Format("pathMarkerArrow{0}", color.Name),
				Fill = new SvgColourServer(color),
				PathData = SvgPathBuilder.Parse(@"M0,0 L4,2 L0,4 L1,2 z")
			};

			arrowMarker = new SvgMarker()
			{
				ID = id,
				MarkerUnits = SvgMarkerUnits.StrokeWidth,
				MarkerWidth = 5,
				MarkerHeight = 5,
				RefX = 3,
				RefY = 2,
				Orient = new SvgOrient() { IsAuto = true },
				Children = { arrowPath }
			};

			defsElement.Children.Add(arrowMarker);
		}
		return arrowMarker;
	}

	protected SvgElement MakeLinkArrow(TPoint parent, TPoint linkedPoint, TPoint delta)
	{
		var color = DoGetLinkColor(linkedPoint);

		var arrowMarker = MakeArrowMarker(color);

		double startX = parent.X + (delta.X + 1.0) / 2.0 * PointSize.Width + 2.0 * delta.X;
		double endX = startX + delta.X * linkSize.Width + -6.0 * delta.X;

		double startY = parent.Y + (delta.Y + 1.0) / 2.0 * PointSize.Height + 2.0 * delta.Y;
		double endY = startY + delta.Y * linkSize.Height + -6.0 * delta.Y;

		return new SvgLine()
		{
			ID = string.Format("lineLinkedPointX{0}Y{1}", linkedPoint.Data.X, linkedPoint.Data.Y),
			StartX = (float)startX,
			StartY = (float)startY,
			EndX = (float)endX,
			EndY = (float)endY,
			Stroke = new SvgColourServer(color),
			StrokeWidth = linkArrowWidth,
			MarkerEnd = new Uri(string.Format("url(#{0})", arrowMarker.ID), UriKind.Relative)
		};
	}

	private SvgElement MakePointRectangle(TPoint Point)
	{
		return new SvgRectangle
		{
			ID = string.Format("rectPointX{0}Y{1}", Point.Data.X, Point.Data.Y),
			X = Point.Data.X,
			Y = Point.Data.Y,
			Width = PointSize.Width,
			Height = PointSize.Height,
			CornerRadiusX = PointSize.Width / 5,
			CornerRadiusY = PointSize.Height / 5,
			Stroke = new SvgColourServer(DoGetPointBorderColor(Point)),
			Fill = new SvgColourServer(DoGetPointFillColor(Point)),
			StrokeWidth = PointBorderWidth
		};
	}

	private void Render()
	{
		if (document != null) return;

		InitializeSVGElements();

		foreach (var Point in Map.Points)
		{
			groupElement.Children.Add(MakePointRectangle(Point));
			groupElement.Children.Add(MakeLinkArrow(Point, Point.Data.LinkedPoint, Point.Data.LinkDirection.Value));
		}
	}

BTW, I really wish you guys added some easier way to add points into a path programmatically, since as you can see, I had to parse a hard coded string into the arrow marker's path.

**Comment by podostro** [comment] 2016-01-02 23:49
Here is a simpler example, compiling code to reproduce it, and the actual output in both the app and in Chrome.  Removed the code from the prior comment.

Application:
![image](https://cloud.githubusercontent.com/assets/2327913/12076626/fa5618a8-b191-11e5-8932-9c988184a0de.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/2327913/12076631/2817569e-b192-11e5-8947-ea0c68ff9690.png)


Code:

	private void button1_Click(object sender, EventArgs e)
	{
		int width = 50;
		int height = 50;

		var document = new SvgDocument()
		{
			ID = "svgMap",
			ViewBox = new SvgViewBox(0, 0, width, height)
		};

		var defsElement = new SvgDefinitionList() { ID = "defsMap" };
		document.Children.Add(defsElement);

		var groupElement = new SvgGroup() { ID = "gMap" };
		document.Children.Add(groupElement);

		var arrowPath = new SvgPath()
		{
			ID = "pathMarkerArrow",
			Fill = new SvgColourServer(Color.Black),
			PathData = SvgPathBuilder.Parse(@"M0,0 L4,2 L0,4 L1,2 z")
		};
		
		var arrowMarker = new SvgMarker()
		{
			ID = "markerArrow",
			MarkerUnits = SvgMarkerUnits.StrokeWidth,
			MarkerWidth = 5,
			MarkerHeight = 5,
			RefX = 3,
			RefY = 2,
			Orient = new SvgOrient() { IsAuto = true },
			Children = { arrowPath }
		};

		defsElement.Children.Add(arrowMarker);

		var line = new SvgLine()
		{
			ID = "lineLinkedPoint",
			StartX = 0,
			StartY = 15,
			EndX = 35,
			EndY = 35,
			Stroke = new SvgColourServer(Color.Black),
			StrokeWidth = 3,
			MarkerEnd = new Uri(string.Format("url(#{0})", arrowMarker.ID), UriKind.Relative)
		};

		groupElement.Children.Add(line);

		txtLog.Text = document.GetXML();
		picRender.Image = document.Draw();
	}

**Comment by HeinrichAD** [comment] 2016-01-03 11:42
Hi podostro,

I searched for the problem and found it.
The problem is the calculate of the position of the MakerEnd element. There are so many "DOTO" marks that I do not know how to fix it. Unfortunately, I have not the time right now to look for a real solution.

I found two solutions for you:
1. I will check in a quick and dirty solution in my repository there your problem should be solved. I hope I will not destroy other cases, but a calculation with zero makes no sense for me.
2. Another solution for you could be the usage of "MarkerUnits = SvgMarkerUnits.UserSpaceOnUse" instead of StrokeWidth for the arrows. The disadvantage is that the arrow size is not correct but this can be corrected by the arrow maker size.

The single arrow looks like this now (1. Solution):
![arrow](https://cloud.githubusercontent.com/assets/5962361/12078456/cbcb6f56-b213-11e5-9dfd-a9ebeca00473.png)

The whole svg like this (1. Solution):
![operatingplan](https://cloud.githubusercontent.com/assets/5962361/12078458/d2ecfb74-b213-11e5-8ab8-5b9561252f40.png)

Feel free to test it.
I would greatly appreciate it if you kindly give me some feedback on this.

**Comment by podostro** [comment] 2016-01-03 18:33
Hi HeinrichAD, it's awesome you could find a fix so quickly :+1: 

I will be testing your fix in a few days, but seeing the screenshots you posted, I think it works fine already!

About solution 2, That actually helps with IE, but unless the client complains; I will probably leave it as is right now.

Thanks a lot!  Should I close the issue o wait till your commit is pulled?

**Comment by tebjan** [comment] 2016-01-03 18:35
looks like a neat pull request... thanks!

**Comment by HeinrichAD** [comment] 2016-01-03 20:32
Hi podostro,
Hi tebjan,

@podostro if you want you can close this issue. I will wait a few days for your feedback. So you can test it. If there are no problems I will create a pull request. [Sorry for this, I am new on GitHub and I will surely need some to create my first pull request ;)]
@tebjan I have some more fixes and new feature. I need a few days to test them and to think about the documentation.

**NOTE:** I only tried to fix this issue. Please notice that the position finding of marker elements with the property "SvgMarkerUnits.StrokeWidth" is not really developed yet. [Nevertheless this should be work for the most cases.]

@podostro I glad I could help you. I need to thank you too. The way you create the SVG over the rendering engine directly was something new for me and interested me. I am sure this will inspire me in the future. Also thanks to the example code. It makes many thinks easier with a code example and Unit Test.
Please update your feedback after you test it.

**Comment by tebjan** [comment] 2016-01-06 17:04
hope this is closed now with the mentioned pull request. otherwise please reopen it.

**Closed by tebjan** 2016-01-06 17:04 UTC
