### ISSUE TITLE
 Cannot process SVG file, cannot allocate the required memory

### ISSUE THREAD

**Issue by Radzhab** [vvvv/SVG#250] opened 2016-09-07 13:39 UTC
I try open one svg file. Its rise error. What i make wrong?

[main.zip](https://github.com/vvvv/SVG/files/459236/main.zip)

**Comment by TDmeteor** [comment] 2017-02-24 17:19
Hi All! I use SVG lib in an ASP.MVC web-app and I'm getting the same error. . ((
After looking at the source code of the SvgDocument.cs file, I have found that actually it's because of a not loaded svg document, thus the Draw() method fails..
It's strange.. but exactly the same code works just fine in a console or GUI app (loaded from an svg file or directly from a xml string). So, what might be wrong for a web-app?

```
using (var xmlStream = new MemoryStream(Encoding.ASCII.GetBytes("xmlString")))
                {
                    xmlStream.Position = 0;
                    var svg = SvgDocument.Open<SvgDocument>(xmlStream);                  
                    var bitmap = svg.Draw();
                }
```

**Comment by mrbean-bremen** [comment] 2019-02-10 11:28
I just checked this, and the original problem is indeed that the bitmap is too large - .NET refuses to allocate that much contiguous memory - not much we can do about this without changing the image.

I have no no idea about the second problem - it could be the same problem (maybe the web app just uses up more memory), or something else - difficult to say without the data.

**Comment by mrbean-bremen** [comment] 2019-02-22 16:43
As this is not a bug in SVG.NET, I copied the answer to [Q&A](https://github.com/vvvv/SVG/wiki/Q&A#why-does-my-application-crash-with-cannot-allocate-the-required-memory) and close this issue.

**Closed by mrbean-bremen** 2019-02-22 16:43 UTC
Labels: crash
