### ISSUE TITLE
how to set dominant-baseline to hanging?

### ISSUE THREAD

**Issue by amiralarab** [vvvv/SVG#284] opened 2017-03-01 15:12 UTC
Hi
I use many fonts to write text element in svg.
when I change font-size, the baseline of text is incorrect for positioning!
cause I have 3 text element with different size dynamically
have you support dominant-baseline to hanging and convert this svg to png?
thanks advance

**Comment by amiralarab** [comment] 2017-03-06 10:16
dominant-baseline not support with this library!

**Comment by cantax** [comment] 2017-04-21 13:12
Same as #298

**Comment by mrbean-bremen** [comment] 2018-12-22 13:42
Closing as duplicate of @298.

**Closed by mrbean-bremen** 2018-12-22 13:42 UTC
