### ISSUE TITLE
SVG is not correctly interpreted, e.g. US-Flag's stars are distributed over the whole graphic

### ISSUE THREAD

**Issue by cbries** [vvvv/SVG#243] opened 2016-07-01 08:48 UTC
It looks like that the "path" is not correctly interpreted:
`<path d="M0,450H7410m0,600H0m0,600H7410m0,600H0m0,600H7410m0,600H0" stroke="#fff" stroke-width="300"/>`  
The resulting "Star" is distributed over the whole graphic.

Example application to reproduce this issue (svg is uncluded):
[WpfApplication1.zip](https://github.com/vvvv/SVG/files/343116/WpfApplication1.zip)

By the way, the svg is copied from Wikipedia:
https://en.wikipedia.org/wiki/United_States#/media/File:Flag_of_the_United_States.svg

![followupissue](https://cloud.githubusercontent.com/assets/5418062/16516633/51ffb238-3f79-11e6-9a5f-efa1f0455f59.PNG)

**Comment by ThisIsRobokitty** [comment] 2016-08-12 03:05
Can confirm, I have the same issue with the most recent source.

**Comment by mrbean-bremen** [comment] 2018-11-20 12:37
Duplicate of #202, both have been fixed some time ago (test is present).

**Comment by mrbean-bremen** [comment] 2018-12-18 20:07
Closing as fixed.

**Closed by mrbean-bremen** 2018-12-18 20:07 UTC
