### ISSUE TITLE
SvgClipPath generates invalid markup for ClipPathUnits

### ISSUE THREAD

**Issue by explunit** [vvvv/SVG#106] opened 2014-11-06 15:38 UTC
```
new SvgClipPath { ID = "myid", ClipPathUnits = SvgCoordinateUnits.Inherit };
```

Once added to the document and serialized out to string for browser, generates warning like this in Chrome:

> Invalid value for <clipPath> attribute clipPathUnits=""

Leaving the ClipPathUnit out of the above declaration results in the same error.

Using this:

```
new SvgClipPath { ID = "myid", ClipPathUnits = SvgCoordinateUnits.ObjectBoundingBox};
```

Gives this error:

> Invalid value for <clipPath> attribute clipPathUnits="objectboundingbox"

The [valid values](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clipPathUnits) are `userSpaceOnUse` or `objectBoundingBox`

**Comment by mrbean-bremen** [comment] 2018-12-22 16:59
Could not reproduce this - seems to be fixed. Closing.

**Closed by mrbean-bremen** 2018-12-22 16:59 UTC
