### ISSUE TITLE
Svg render wrong

### ISSUE THREAD

**Issue by DrEight** [vvvv/SVG#524] opened 2019-07-23 08:24 UTC
Hello,
I have a problem with the attached svg that it does not render correctly.
See the results>
<img width="1229" alt="svgNotRender" src="https://user-images.githubusercontent.com/5313322/61695156-48edeb80-ad33-11e9-9973-32c10c161363.png">

Library version 2.4.2 with the framework 4.6.1.

Attached there is the svg
[SVG_Layout.zip](https://github.com/vvvv/SVG/files/3420951/SVG_Layout.zip)

Any Idea ?

**Comment by mrbean-bremen** [comment] 2019-07-23 19:32
I can reproduce this with version 2.4.2 and 2.4.3, but not with master - so this seems to be fixed in master.
You may try the 3.0 pre-release, compile master yourself, or wait for the next release which is probably around the corner (ping @tebjan).

**Comment by mrbean-bremen** [comment] 2019-07-23 19:35
This is how it looks in master:
![grafik](https://user-images.githubusercontent.com/4623701/61741686-b6c90000-ad91-11e9-8a7e-3be21bfde4fa.png)

**Comment by mrbean-bremen** [comment] 2019-07-23 19:37
Though the location of the number is not quite correct here either... probably a font rendering problem.

**Comment by mrbean-bremen** [comment] 2019-07-23 19:41
Ok, the attribute `alignment-baseline` is not supported, see #263 - that explains it.

**Comment by mrbean-bremen** [comment] 2019-07-24 18:03
Ok, the reason why this was not rendered is that an ID starts with a number - which is invalid svg, but is now supported (see #138).
Closing as duplicate, and fixed in master.

**Closed by mrbean-bremen** 2019-07-24 18:03 UTC
