### ISSUE TITLE
Text elements are not displayed

### ISSUE THREAD

**Issue by SFreiheit** [vvvv/SVG#419] opened 2019-02-20 17:00 UTC
Hello I use the version 2.4.1.32115 as DLL under Visual Basic.net. It works too. Unfortunately, no text elements are shown. no matter what I do, the text is not displayed.

If I open the SVG file with a browser, I can see the text.

This is my SVG:
`<?xml version="1.0" encoding="utf-8" standalone="no"?><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="seatplan"><text x="130" y="80" text-anchor="middle" fill="black">Stage</text><rect id="stage" x="100" y="50" width="100" height="50" fill="white" stroke="black" /></svg>`

did I do something wrong or is this a bug in the DLL?

**Comment by mrbean-bremen** [comment] 2019-02-20 17:15
Hm, if I open your SVG in a browser (I tried Chrome, Firefox and IE) I see only a rectangle without text.
Which browser did you use? Are you sure this is the correct SVG?

**Comment by mrbean-bremen** [comment] 2019-02-20 17:17
The problem is that the text is hidden by the white rectangle.

**Comment by mrbean-bremen** [comment] 2019-02-20 17:28
Ok, if removing the white rectangle, or moving it before the text, the text is not displayed anyway with SVG (but is in browser), so this is probably a bug.

**Comment by mrbean-bremen** [comment] 2019-02-20 17:41
The problem seems to be the default font size - if you set the font-size attribute in your text or svg element to a defined value (e.g. something like `font-size="16pt"`) it will work. Setting the font-size to something like "medium" or "small" also does not work.

**Comment by mrbean-bremen** [comment] 2019-02-20 18:43
Ok, I will check-in a fix now. Note:
- the shown font (size and type) may be different from the one shown in the browser - both default font-size and font family are not fixed to a concrete value
- if you don't build SVG.NET yourself, you will have to wait for the next nuget release (which probably is not far away)

**Closed** 2019-02-20 18:43 UTC
Labels: bug

**Comment by SFreiheit** [comment] 2019-02-21 11:23
Excuse me, I had tried several things.
I had the svg file with MS Eage Tried.
But I had another try with groups

`<?xml version="1.0" encoding="utf-8" standalone="no"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="seatplan">
	<g>
		<rect id="stage" x="100" y="50" width="100" height="50" fill="white" stroke="black" />
		<text x="130" y="80" fill="black">Stage</text>
	</g>
</svg>`

Microsoft Eage show Box and Text but in my Programm i see only the box

**Comment by SFreiheit** [comment] 2019-02-21 11:24
i try now to set the font size

font-size="16p

**Comment by SFreiheit** [comment] 2019-02-21 11:28
okay when i set the font-size it is working

**Comment by mrbean-bremen** [comment] 2019-02-21 11:47
Yeah, as I wrote, the default font size is incorrect (it is basically set to zero, so that the text is not visible). Will be fixed in the next release.

**Comment by SFreiheit** [comment] 2019-02-21 11:47
thanks for the Help
