### ISSUE TITLE
Render svg to cairo context?

### ISSUE THREAD

**Issue by cambiata** [vvvv/SVG#156] opened 2015-06-07 09:00 UTC
Is it possible to render svgs to a cairo context?
If not, what would it take to implement that? Implement a new renderer using the ISvgRenderer interface, or?

/ Jonas

**Comment by zwcloud** [comment] 2015-08-29 10:43
Hi! Are you make any progress now?
I'm trying implement the ISvgRenderer interface with Mono.Cairo(a C# binding of cairo from the mono project).
But the problem is that Mono.Cairo uses ImageSurface instead of a System.Drawing.Image.

**Comment by mrbean-bremen** [comment] 2019-01-04 12:36
This is quite old now. The answer to the first question (possible to render) is obviously no.
As @zwcloud has pointed out, `ISvgRenderer` depends on `System.Drawing.Image`, so it cannot be used as is as base for Mono.Cairo.
Either you need to use conditional compilation, as done in PR #326, or have to abstract `System.Drawing.Image`. Both of these options are not simple, as far as I can see, but may be doable.
Closing.

**Closed by mrbean-bremen** 2019-01-04 12:36 UTC
Labels: question
