### ISSUE TITLE
Publish a dotnet core version 

### ISSUE THREAD

**Issue by GeekEz** [vvvv/SVG#494] opened 2019-06-19 09:31 UTC
Hi, @tebjan 

it would be great if you could push a dotnet core version to nuget.

thanks

**Comment by tebjan** [comment] 2019-06-19 13:35
hi @GeekEz i've just published a preview version here: https://www.nuget.org/packages/Svg/3.0.3-gecdc54b12b

let me know whether it works...

**Comment by GeekEz** [comment] 2019-06-20 02:13
thanks @tebjan 

I'm test it on dotnet core 2.2.x , seems it's not worked. Also i'm pull the source code, looks like the Svg project already include for dotnet core 2.2 build. I'm build and try it by myself. It worked perfect.

**Comment by mrbean-bremen** [comment] 2019-06-20 05:56
@tebjan - looks like there have been some merge problems in the Netcore2.2 branch. Maybe it is easier to make a new branch from master and cherry-pick (or manually add) the wanted changes, and make a new PR.

**Comment by gvheertum** [comment] 2019-08-09 17:51
@tebjan I this not answered in and/or related to #522 ? In that case this question might be flagged as resolved?

**Comment by mrbean-bremen** [comment] 2019-08-10 15:04
I'm closing this as duplicate of #522 (it should be the other way around, but in that issue is the more recent information).

**Closed by mrbean-bremen** 2019-08-10 15:04 UTC
Labels: question
