### ISSUE TITLE
Doesn't render stroke of rect, if fill opacity is 0

### ISSUE THREAD

**Issue by AnReZa** [vvvv/SVG#437] opened 2019-04-18 12:06 UTC
I realized, that this SVG lib doesn't render the border of rectangles, when the fill opacity is set to 0:
```svg
<rect id="SvgjsRect1008" width="313" height="448" stroke-opacity="1" stroke="#ff0d28" stroke-width="3" fill-opacity="1" fill="rgba(0, 0, 0, 0)" x="360" y="48" />
```

This example will render the stroke in the same opacity as the fill color. So it's not rendered at all in this example. This, as far as I know, doesn't correspond to the SVG standard.

**Comment by mrbean-bremen** [comment] 2019-04-18 18:09
This is actually a regression I introduced myself in [this commit](https://github.com/vvvv/SVG/commit/a234a72b4d3dad09530d531494fe3385f0d9bd90). Should work in 2.4.1...

**Comment by mrbean-bremen** [comment] 2019-04-18 18:51
As far as I can see, this will be fixed by #433.

**Comment by H1Gdev** [comment] 2019-04-19 09:51
@mrbean-bremen 

Checked with the following SVG.

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" width="700" height="200" xml:space="preserve">
<rect width="50" height="100" stroke-opacity="1" stroke="rgba(255, 0, 0, 0)" stroke-width="6" fill-opacity="1" fill="rgba(0, 0, 255, 0)" x="100" y="40" />
<rect width="50" height="100" stroke-opacity="1" stroke="rgba(255, 0, 0, 255)" stroke-width="6" fill-opacity="1" fill="rgba(0, 0, 255, 255)" x="100" y="40" />
<rect width="50" height="100" stroke-opacity="1" stroke="rgba(255, 0, 0, 127)" stroke-width="6" fill-opacity="1" fill="rgba(0, 0, 255, 127)" x="160" y="40" />
<rect width="50" height="100" stroke-opacity="1" stroke="rgba(255, 0, 0, 1)" stroke-width="6" fill-opacity="1" fill="rgba(0, 0, 255, 1)" x="220" y="40" />
<rect width="50" height="100" stroke-opacity="1" stroke="rgba(255, 0, 0, 1)" stroke-width="6" fill-opacity="1" fill="rgba(0, 0, 255, 1)" x="280" y="40" />
<rect width="50" height="100" stroke-opacity="0.5" stroke="rgba(255, 0, 0, 255)" stroke-width="6" fill-opacity="0.5" fill="rgba(0, 0, 255, 255)" x="340" y="40" />
</svg>
```

In Firefox and Chrome, It is hidden when alpha value is 0 and displayed when alpha value is 255.
But not transparent.

**Comment by AnReZa** [comment] 2019-04-23 06:36
It's nice to hear, that a fix is already available. Will there be an official release soon?

**Comment by nmgo** [comment] 2019-04-23 12:36
I'm also seeing an issue with "fill-opacity", although I'm not sure if this is the problem as reported in this issue.

The svg markup is as follows:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="225" height="200">
  <g id="Layer 1">
    <path d="M150 0 L75 200 L225 200 z" fill-opacity="0" stroke="red" stroke-width="1" />
  </g>
</svg>
```

Expected rendering:
![triangle_fill-opacity_expected](https://user-images.githubusercontent.com/49908665/56580761-3c8ab300-65cb-11e9-8e96-64711e313b6a.png)

Result using 6ca410096bf231692600126a86f771dff21eb878 and using H1Gdev's 8fa0c66daad2a106565f819fe442c9c347b0e8c5:
![triangle_fill-opacity_result](https://user-images.githubusercontent.com/49908665/56580762-3d234980-65cb-11e9-90fc-3fd167868a6d.png)

**Comment by AnReZa** [comment] 2019-04-24 07:48
Can you please provide a quick hotfix release with the lastest changes and bugfixes for this issue?

**Comment by NMGo** [comment] 2019-04-24 10:08
As per my comment in #439, the issue I reported above appears to be fixed as of H1Gdev's commit 7f392c318d8dc20caba5d16ee053994b3f997ffb (branch "opacity").

Thank you, @H1Gdev and @mrbean-bremen, for your assistance.

**Closed** 2019-04-24 18:01 UTC
Labels: bug

**Comment by mrbean-bremen** [comment] 2019-04-24 18:14
@H1Gdev - are you done fixing, or do you want to add more PRs?

@tebjan: provided @H1Gdev is done - he did a good job fixing these opacity issues, which partly have been regressions. Maybe it makes sense to make another minor release (as asked by @AnReZa)?

**Comment by H1Gdev** [comment] 2019-04-24 20:38
@mrbean-bremen 

Yes.fix all my PRs.

**Comment by AnReZa** [comment] 2019-05-07 13:25
@mrbean-bremen @tebjan Any chance to get a minor release for this fix? I would be really thankful! :)

**Comment by tebjan** [comment] 2019-05-07 14:17
yes, sounds good! will make a new release.

**Comment by tebjan** [comment] 2019-05-07 14:23
done, thanks for the fixes @H1Gdev and @mrbean-bremen!

**Comment by tebjan** [comment] 2019-05-07 14:46
takes usually 30 minutes to be listed on nuget org. https://www.nuget.org/packages/Svg/2.4.3

**Comment by AnReZa** [comment] 2019-05-07 15:05
Thank you!

**Comment by NMGo** [comment] 2019-05-13 06:58
> takes usually 30 minutes to be listed on nuget org. https://www.nuget.org/packages/Svg/2.4.3

There is no reference to #437 on the release notes for 2.4.3.

Thank you for making this happen.

**Comment by mrbean-bremen** [comment] 2019-05-13 07:21
Looks like the release notes on the nuget page belong to 2.4.2 - you can check the [release notes in the Wiki](https://github.com/vvvv/SVG/wiki/Release-Notes).
