### ISSUE TITLE
SvgImage.cs completion

### ISSUE THREAD

**Issue by naxtell** [vvvv/SVG#15] opened 2013-09-01 01:58 UTC
Through troubleshooting pattern images not showing up, I've found that SvgImage.cs appears to be incomplete. I'm attempting to complete this class and would like to ask for any suggestions or even a dev copy, if one exists. Here's a simplified example showing the image pattern that I'm attempting to render. Thanks for any assistance, Nate.

http://naxtell.com/test-waves.svg

Edit: Replaced svg code with link to my svg file.

**Comment by mrbean-bremen** [comment] 2018-12-17 18:08
Checked with the given test image - works fine, the issue is fixed with the merged PR.

**Closed by mrbean-bremen** 2018-12-17 18:08 UTC
