### ISSUE TITLE
Incorrect rendering with LinearGradiantServer

### ISSUE THREAD

**Issue by Itori** [vvvv/SVG#754] opened 2020-07-27 11:57 UTC
#### Description
No Stop rendering when using a Gradiant

#### Example data
Rendering is the following:
<linearGradient id="grad"></linearGradient>

#### Used Versions
tested on master and on 3.1.1

Added the test
[LinearGradiantServerTest.txt](https://github.com/vvvv/SVG/files/4981846/LinearGradiantServerTest.txt)

**Comment by H1Gdev** [comment] 2020-07-27 13:12
Please set `Stops` as follows.

```cs
gradiant.Children.Add(new SvgGradientStop() { Offset = 0.25f, StopColor = new SvgColourServer(Color.Black) });
gradiant.Children.Add(new SvgGradientStop() { Offset = 0.50f, StopColor = new SvgColourServer(Color.Gray) });
gradiant.Children.Add(new SvgGradientStop() { Offset = 0.75f, StopColor = new SvgColourServer(Color.White) });
```

**Comment by Itori** [comment] 2020-07-27 14:21
Thanks, this is working.

I keep it open as this correction seems to be a workaround more than a standard usage.

**Comment by H1Gdev** [comment] 2020-07-27 23:15
> I keep it open as this correction seems to be a workaround more than a standard usage.

I'm not sure what you want, but this is the only way.

`Stops` property is read-only property that only `SvgGradientStop` will be set by children.
As far as I can see implementation, I think this property should be `protected`.

Also, second argument is not working for the constructor you were using.

**Comment by mrbean-bremen** [comment] 2020-12-27 15:01
Closing this as not a bug.

**Closed by mrbean-bremen** 2020-12-27 15:01 UTC
