### ISSUE TITLE
Radial gradient not rendered in button image

### ISSUE THREAD

**Issue by Emasoft** [vvvv/SVG#83] opened 2014-07-11 23:58 UTC
Trying to loading a simple svg button ("UIButton.svg") crashes the library.

The SVGViewer exits with the following error:

```
System.ArgumentException: Invalid ColorBlend object. The positions array must have 1.0 as its last element.
  at System.Drawing.Drawing2D.LinearGradientBrush.set_InterpolationColors (System.Drawing.Drawing2D.ColorBlend value) [0x00077] in /Volumes/build-root-ramdisk/mono-3.4.0/mcs/class/System.Drawing/System.Drawing.Drawing2D/LinearGradientBrush.cs:196 
```

The SVG file is correctly rendered by Chrome. Here is a screenshot:
![UIButton.svg](https://cloud.githubusercontent.com/assets/713559/3560001/38a5dfde-0956-11e4-941c-d0203c249665.png)

You can download the UIButton.svg file from this fiddle:
http://jsfiddle.net/EmanueleS/ve3XN/

**Comment by mrbean-bremen** [comment] 2018-12-20 20:39
Wit the currrent version, it looks like this:
![grafik](https://user-images.githubusercontent.com/4623701/50309432-19c28380-049f-11e9-9561-97bace5c4962.png)
So the crash and the text issues are gone, but the radial gradient seems not to be rendered.
Adapting issue title.

**Comment by mrbean-bremen** [comment] 2019-01-01 17:42
Update: after another fix related to feMerge, the button looks like this:
![grafik](https://user-images.githubusercontent.com/4623701/50574996-f29b7880-0df3-11e9-8984-41cf11e60d88.png)
The problem is only the shadow, which is created by a filter. If removing the filter, the button looks good (but without shadow):
![grafik](https://user-images.githubusercontent.com/4623701/50575041-c3393b80-0df4-11e9-9d25-5b356da93a17.png)
As the filters not working are handled in #43, I'm closing this issue.

**Closed by mrbean-bremen** 2019-01-01 17:42 UTC
Labels: bug

**Comment by mrbean-bremen** [comment] 2019-05-12 18:57
Turns out the problem have not really been the filters in this case, but the parsing of float numbers in the color matrix on non-English systems. Here is the current rendering for reference:
![grafik](https://user-images.githubusercontent.com/4623701/57586620-809d1380-74f8-11e9-9646-1a39a952ac83.png)
