### ISSUE TITLE
DeepCopy on SvgGradientStop doesn't copy StopColor

### ISSUE THREAD

**Issue by robertvo** [vvvv/SVG#350] opened 2017-12-31 07:37 UTC
DeepCopy in SvgGradientStop 
The stop-color is not copied 

		public override SvgElement DeepCopy<T>()
		{
			var newObj = base.DeepCopy<T>() as SvgGradientStop;
			newObj.Offset = this.Offset;
                        _newObj.StopColor = this.StopColor;_
			return newObj;
		}

**Comment by mrbean-bremen** [comment] 2019-01-05 19:56
Actually, this is not a bug - the stop color is not a separate member, but read from an attribute which is copied by the base class. Closing.

**Closed by mrbean-bremen** 2019-01-05 19:56 UTC

**Comment by robertvo** [comment] 2019-01-14 19:45
well, when I did a deep copy of a document, lots of gradient surfaces were black. So that appeared as a bug

**Comment by mrbean-bremen** [comment] 2019-01-14 19:47
Ok, that sounds indeed like a bug - do you have an example file to reproduce this?
