### ISSUE TITLE
I am just curious if project is being maintained?

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#358] opened 2018-03-30 07:48 UTC
Hello everyone,

It looks like there were updates to the project for over a year now. There are pending pull requests that address several important issues, but nothing has been merged.

So is anyone maintaining this project? And if no how can we bring it back to life?

Thanks

**Comment by tebjan** [comment] 2018-03-30 20:31
hey, i don't find the time to code review the PRs often. from my experience PRs often introduce new bugs, so it's quite time consuming to review all code and go thru the tests. i can however just merge the PRs and revert the changes later if problems occurs... would be a less time consuming strategy.

**Comment by mrbean-bremen** [comment] 2018-11-20 14:50
I also noticed that there are quite some old issues that are either fixed, have insufficient information, or are questions that are partly answered. Or duplicates... like this one is a duplicate of #343.

I would suggest to cleanup some of the issues (I could help to check if they are fixed, if I find some time), and maybe use labels like "question", "bug" or "enhancement", so contributors can see where they can help. It would be nice if this helpful library could live on...

Also, it may make sense to add a PR template that requests a test for each PR, and points to instructions how to run all tests to avoid at least regressions for existing tests.

**Comment by mrbean-bremen** [comment] 2018-12-18 17:46
Closing this as answered... project is still being maintained.

**Closed by mrbean-bremen** 2018-12-18 17:46 UTC
