### ISSUE TITLE
NullReferenceException when rendering a file

### ISSUE THREAD

**Issue by mc0re** [vvvv/SVG#345] opened 2017-11-06 12:18 UTC
This file raises a null-pointer exception in the GaussianBlur filter.

Code (WinForms, VB.NET):
```
Const SvgPath = "C:\...\Resources\test1.svg"
Dim mSvg = SvgDocument.Open(SvgPath)
mSvg.Width = PictureBox1.Width
mSvg.Height = PictureBox1.Height
Dim bmp = mSvg.Draw()
PictureBox1.Image = bmp
```
[test1.zip](https://github.com/vvvv/SVG/files/1446132/test1.zip)

**Comment by beastlike** [comment] 2017-12-19 01:51
throws the same error on .Draw() for this fairly simple SVG file as well, generated by SVG-edit...
[simple.zip](https://github.com/vvvv/SVG/files/1570031/simple.zip)

If anyone can recommend a production-ready SVG library for .NET please do!

**Comment by mc0re** [comment] 2017-12-19 13:17
SharpVectors?

**Comment by beastlike** [comment] 2017-12-20 13:34
It appears that these **&quot;s** were causing the problem in my case:
`marker-start="url(&quot;#se_marker_start_svg_4&quot;)" marker-end="url(&quot;#se_marker_end_svg_4&quot;)"`

I looked in your svg xml @mc0re  but I wasn't able to fix anything in there that would make it render.

however, now I get this:
![image](https://user-images.githubusercontent.com/8137927/34209505-6a9fabc0-e560-11e7-88fe-6df86d3a9aa7.png)

**Comment by mc0re** [comment] 2017-12-20 14:18
It's not the XML that should be fixed but the code :-)

**Comment by mrbean-bremen** [comment] 2019-01-05 20:02
I cannot reproduce the crash with both the example files (they are added to the test files).
The other issue with the marker arrows is already mentioned in another issue - closing this one.

**Comment by mrbean-bremen** [comment] 2019-01-05 20:17
Ah, sorry, the first example still crashes - reopen.

**Closed** 2019-01-24 19:53 UTC
Labels: bug, crash

**Comment by mrbean-bremen** [comment] 2019-01-24 19:55
The first example now renders correctly except for the arrow direction handled in #215.

**Comment by mrbean-bremen** [comment] 2019-01-27 19:13
Arrow direction is now fixed (and it was a separate problem unrelated to #215).
