### ISSUE TITLE
Text does not render when converting specific SVG to PNG

### ISSUE THREAD

**Issue by centDejan** [vvvv/SVG#324] opened 2017-05-30 11:49 UTC
Hi!

I have this issue that is making me crazy. For couple of days I am trying to bypass it, but no success.

I create SVG using fantastic Fabric.JS library. Until I edit the text on this component (IText), export is working. Once I edit/change text in the component, the component creates SVG group with a lots of TSpan's that do not get converted with the library. Only first letter is visible.

Is there any bypass?

For the reference I have included SVG that does not render correctly.

Thanks in advance for your valuable feedback!

[not_exportable_to_pdf.zip](https://github.com/vvvv/SVG/files/1038153/not_exportable_to_pdf.zip)

**Comment by Eskora** [comment] 2017-06-29 02:06
Hi centDejan,

I'm facing the same problem, have you finally found a solution ?

Thank you.

**Comment by centDejan** [comment] 2017-06-29 08:25
I solved this issue by using another library - Magick.net.

**Comment by tburnett80** [comment] 2017-07-08 19:31
I am noticing this as well, generating svg graphs with C3.js / D3.js and trying to render the svg as a png image to insert into a downloadable report.

It seems like the tspan text is just completely ignored.

**Comment by haykpetros** [comment] 2017-08-14 18:17
Hello @centDejan and @tburnett80,

This is same as Issue #318.

Thanks

**Comment by mrbean-bremen** [comment] 2018-12-18 18:36
Closing as duplicate of #318.

**Closed by mrbean-bremen** 2018-12-18 18:36 UTC
