### ISSUE TITLE
Filters are broken?

### ISSUE THREAD

**Issue by g40** [vvvv/SVG#127] opened 2015-02-11 13:35 UTC
I've just spent an interesting time stepping through some code to test the various filter effects with a view to adding some new ones. Sadly none seem to work - I'm working off a forked master. Has anyone got a working filter example?

This _should_ work without any problems 

```
<svg width="600" height="250" viewBox="0 0 600 250"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
<defs>
    <filter id="blurFilter4" x="-20" y="-20" width="200" height="200">
        <feGaussianBlur in="SourceGraphic" stdDeviation="10" />
    </filter>
</defs>
<rect x="20" y="20" width="90" height="90"
      style="stroke: none; fill: #00ff00; filter: url(#blurFilter4);" />
</svg>
```

Rendered in Firefox: 

![image](https://cloud.githubusercontent.com/assets/812250/6022807/6f3c16ea-abb7-11e4-8973-432e93713612.png)

**Comment by mrbean-bremen** [comment] 2018-12-21 18:46
Filters are still broken. Closing as duplicate of #43.

**Closed by mrbean-bremen** 2018-12-21 18:46 UTC
