### ISSUE TITLE
SvgText not render

### ISSUE THREAD

**Issue by RamJha** [vvvv/SVG#192] opened 2015-09-11 12:05 UTC
Hi,
I am not able to render text by SvgText object.
 FSvgDoc = new SvgDocument
            {
                Width = 500,
                Height = 500
            };

```
        FSvgDoc.ViewBox = new SvgViewBox(-250, -250, 500, 500);
        var t = new SvgText();

        var group = new SvgGroup();
```

   FSvgDoc.Children.Add(group);

group.Children.Add(new SvgText
{
    Text = "ram krishna",
X = new SvgUnitCollection {new SvgUnit(200)},
    Y = new SvgUnitCollection { new SvgUnit(200) },

}

);

 var stream = new MemoryStream();
        FSvgDoc.Write(stream);

```
pictureBox1.Image = FSvgDoc.Draw();
```

Plz help me.

**Comment by w0q** [comment] 2015-09-14 04:31
Also encountered the same problem.The text is not rendered if the tag \<text\> contains no child elements. The following code displays the text: 
svgText.Nodes.Add(new SvgContentNode(){ Content = "some text" }).

**Comment by ChrisPurves** [comment] 2015-11-19 15:09
Thanks! 

Is this not a bug?

**Comment by schoetbi** [comment] 2016-03-29 11:46
It might be clearer if the SvgText would not have a Text Property

**Comment by mrbean-bremen** [comment] 2018-12-19 21:07
Closing as answered.

**Closed by mrbean-bremen** 2018-12-19 21:07 UTC
