### ISSUE TITLE
Are there any plans to release updated NuGet package?

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#382] opened 2018-12-18 21:10 UTC
Hi,

I see that @mrbean-bremen is merging some pull requests and updates the project, so I was wondering if  there is an ETA on when we can expect NuGet package to be updated?

Thanks

**Comment by mrbean-bremen** [comment] 2018-12-27 20:30
@tebjan - from my perspective, this is ready for a NuGet release now (the regression has been fixed). Maybe wait a bit for any more regressions to show up...

**Comment by tebjan** [comment] 2019-01-01 19:08
yes, we can however release a 2.4 nuget preview. might get some people on bord to test it.

**Comment by tebjan** [comment] 2019-01-01 22:50
published latest release build: https://www.nuget.org/packages/Svg/

**Comment by haykpetros** [comment] 2019-01-02 07:41
@tebjan great!

**Comment by tebjan** [comment] 2019-01-05 16:39
there seems to be a new bugfix commit, i'll make an updated nuget soon.

**Comment by mrbean-bremen** [comment] 2019-01-08 10:33
@tebjan - feel free to make the release without integrating the latest fixes - they are not that important, I think, and you can always make a new release (not sure how much effort is a nuget release, though).

**Comment by mrbean-bremen** [comment] 2019-01-08 19:47
Ok, thanks, I hoped for that!

**Comment by tebjan** [comment] 2019-01-08 20:06
it's up: https://www.nuget.org/packages/Svg/2.4.0

**Comment by mrbean-bremen** [comment] 2019-01-08 21:32
I added a [release notes](https://github.com/vvvv/SVG/wiki/Release-Notes) page to the Wiki (or should that better be a file?) for reference.
Closing this one too as answered...

**Closed by mrbean-bremen** 2019-01-08 21:32 UTC
Labels: question
