### ISSUE TITLE
Memory leak when drawing files opened from memory stream with linked images (?)

### ISSUE THREAD

**Issue by ghost** [vvvv/SVG#118] opened 2015-01-08 17:40 UTC
I am trying to write a little console application to do some sort of batch processing on huge amounts of files and noticed the memory usage constantly going up with the number of files processed.

I think I tracked down the problem to a combination of two things:
- the SVG files contain a linked image, and
- I create the `SvgDocument` from a `MemoryStream`.

Test case:
- SVG file "test.svg":

``` xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="800" height="600" viewBox="0 0 800 600">
<image x="0.0" y="0.0" width="800px" height="600px" xlink:href="test.bmp"/>
<text x="100.0" y="100.0" style="font-family:Arial;font-size:20pt;font-style:normal;font-weight:normal;fill:#000000">Linked image test</text>
</svg>
```
- 800x600x24bpp bitmap file "test.bmp" created with GIMP, filled #ffffff
- Test application:

``` vb.net
Imports Svg
Imports System.Drawing
Imports System.IO
Imports System.Text

Module MainModule

    Sub Main()
        Dim ctr As Long = 0
        Dim svg As SvgDocument
        Dim text As String

        ' This would work for all SVG files:
        'svg = SvgDocument.Open(Of SvgDocument)("d:\test.svg")

        ' For SVG files with linked images, this dies at ~1000 iterations, the
        ' GC.Collect() does *not* help.
        Using sr As New StreamReader("d:\test.svg")
            text = sr.ReadToEnd
        End Using

        ' Do whatever with text here. (In my case: replace special chars in
        ' <text> elements that would make the XmlTextReaderImpl throw an
        ' XmlException).

        Dim bytes() As Byte = Encoding.UTF8.GetBytes(text)

        Using ms As New MemoryStream(bytes)
            svg = SvgDocument.Open(Of SvgDocument)(ms)
        End Using

        While (True)
            ctr += 1

            Try
                svg.Draw()
            Catch ex As ArgumentException
                Console.WriteLine("Died at: " & ctr)
                Throw
            End Try

            If (ctr Mod 10 = 0) Then
                GC.Collect()
            End If
        End While
    End Sub

End Module
```

For now I just commented the `SvgImage` class out, recompiled and switched to combining the image and overlay graphics myself.

Or maybe I am just doing something wrong here?

**Comment by mrbean-bremen** [comment] 2019-02-27 20:23
I just tried this in C#, and if I leave out the garbage collector, it runs out of memory after a bit more than 1000 iterations - this is to be expected, as the returned bitmaps never get garbage collected inside that loop. I also noticed that the behavior solily depended on the image size - the presence of the referenced image did not do much of a difference to me.
With the GC, I could not reproduce the problem though. After 100000 iterations, the memory consumtion got barely up.
So I guess that either something went wrong withe the garbage collection, or the memory leak is meanwhile fixed. Closing.

**Closed by mrbean-bremen** 2019-02-27 20:23 UTC
