### ISSUE TITLE
Style attribute is ignored, everything is black

### ISSUE THREAD

**Issue by asyschikov** [vvvv/SVG#137] opened 2015-03-17 00:21 UTC
Hi! I am running SVG.net on Mac+mono.
My problem is that everything is black. I took your example svg (with three circles) and they are black.
I debugged SVG.net and I think I found out why they are black, because SvgElement.Fill returns default value, because this.Attributes["fill"] is equals to null. Well, indeed there is no such attribute, because it is set in style attribute, and value is not pulled from there. It is strange that this.Attributes contains only 1 element "transform". Any idea what is going wrong? Thanks!

**Comment by haykpetros** [comment] 2015-03-22 21:25
Hi,
I believe this is a duplicate of [Issue 131](https://github.com/vvvv/SVG/issues/131) I already reported.
Thanks

**Comment by asyschikov** [comment] 2015-03-22 21:27
@haykpetros yeah maybe, actually I took branch/tag nuget1.7 and it works there.

**Comment by haykpetros** [comment] 2015-03-22 22:23
I've noticed that as well, but nobody updated actual NuGet package itself and I don't have API key to do it myself.

**Comment by tebjan** [comment] 2015-03-23 11:11
if you know the place in the code, it would be very helpful if you could make a pull request. thanks!

**Comment by asyschikov** [comment] 2015-03-23 11:14
@tebjan I thought I do, but well I looked more and understood that it is more complicated than that. Basically style values work in branch nuget1.7 and totally don't work on master. This is very easy to reproduce and to locate the breaking commit from nuget revision to master head.

**Comment by prateek14** [comment] 2018-02-24 11:54
+1 any updates / workarounds?

**Comment by mrbean-bremen** [comment] 2018-12-21 19:41
As the example in #131 works now, I guess this is also fixed, as it is basically a duplicate.
Please reopen if you have a failing example.

**Closed by mrbean-bremen** 2018-12-21 19:41 UTC
