### ISSUE TITLE
Odd number of elements in stroke-dasharray of Svg Path 

### ISSUE THREAD

**Issue by ubbn** [vvvv/SVG#199] opened 2015-09-20 17:54 UTC
When the odd number of elements is given in stroke-dasharray for svg path, the next repetition of array starts from again dash. It means last and first elements are summed up and rendered a dash. It is how System.Drawing handles Pen.DashPattern while in browsers, the next repetition of dash-array starts from a space. 

``` xml
<path stroke-dasharray="50,20,50" d="M0 100 l500 0"  />
```

First image is on SVG lib, second is on browser

![dashes](https://cloud.githubusercontent.com/assets/1505531/9982096/a44ae4e2-5fd0-11e5-8845-2c034a47e9d4.png)

**Comment by mrbean-bremen** [comment] 2019-01-03 09:52
This is actually a duplicate of #58 and [has been fixed](https://github.com/vvvv/SVG/commit/13d66a39914fd05baa3f852a92b076febf322bad).

**Closed by mrbean-bremen** 2019-01-03 09:52 UTC
Labels: bug
