### ISSUE TITLE
Next version?

### ISSUE THREAD

**Issue by ojmoreno** [vvvv/SVG#522] opened 2019-07-22 15:23 UTC
Hello,
when is planned to release the next version on NuGet? 2.4.4 or 2.5.0 or 3.0.0 ?
Best regards

**Comment by mrbean-bremen** [comment] 2019-07-22 17:14
@tebjan - this is for you :)

**Comment by kiwiingenuity** [comment] 2019-07-23 04:45
I'm working on a project that deploys .Net Core 3.0.  Currently working with the v3.0.0-preview6 SDK.
I'm soon wanting to create SVG drawing from scratch.
What are the options available to me, to make the SVG.DLL work with my environment?

If the option is to create another branch, then Tebjan can you give me a hint as to what is involved?

**Comment by gvheertum** [comment] 2019-07-25 11:37
> What are the options available to me, to make the SVG.DLL work with my environment?

If you download/clone this repository (or fork it to a local copy) you can compile the sources. The current master branch of the project is core 2.2 compatible, so if you perform a build targeted on donetcore you should get a DLL you can include in your project.

Just run the command below in the /Sources/ folder
```
dotnet build -c release -f netcoreapp2.2 Svg.csproj
```
this should put the dll you want in the bin/Release/netcoreapp2.2/ folder (or release if you build release)

**Comment by kiwiingenuity** [comment] 2019-07-25 20:45
@gvheertum - I can confirm your solution works! 
The other day I cloned the Master, did a Release build... the required DLL was in the core 2.2 folder.

**Comment by mrbean-bremen** [comment] 2019-07-26 17:55
@gvheertum - can you add an instruction for building the library to Q&A? As you already did an entry there ;)
Actually this is something that belongs to a "Getting started" page - what do think, shall we add a new Wiki page for the time being (in the long run, we may use GitHub pages for this)?

**Comment by gvheertum** [comment] 2019-07-26 19:28
Sure, I’ll try to look into this tomorrow. I’ll attempt to get something like a “getting started” crafted with some basic instructions and references to examples and the faq, which might be a nice starting point for new users.

Not sure indeed if the wiki is the best tool for this or whether we should switch to github pages, but to be honest I’m in no way an expert with regard to the best tooling/methods for this kind of stuff.

**Comment by mrbean-bremen** [comment] 2019-07-26 20:09
Thanks! I'm planning to setup GitHub pages some time, just don't know when I'll get to it. I see the Wiki as a temporary place to collect some documentation. Any documentation is an improvement!

**Comment by gvheertum** [comment] 2019-07-27 12:12
> Any documentation is an improvement!

I like the way you think ;)

**Comment by gvheertum** [comment] 2019-07-27 12:45
@mrbean-bremen, can you have a look at: https://github.com/vvvv/SVG/wiki/Getting-started

I think this might cover a large part of the getting started. Maybe we can update the Readme.md in the project with references to the Wiki and/or add/move parts of the wiki to the Readme.md. This might be helpful for people downloading the sources, since the readme.md will be included in the sources.

**Comment by mrbean-bremen** [comment] 2019-07-27 14:40
Very nice, I like that! A very comprehensive guide for starting to use the library - we should definitely point the Readme to it, and now we have a real starting point for future documentation 👍

**Comment by mrbean-bremen** [comment] 2019-07-27 15:19
I updated the [Readme](https://github.com/vvvv/SVG/blob/master/README.md) and the [documentation issue](https://github.com/vvvv/SVG/issues/401) with a link to the new page.

**Comment by tebjan** [comment] 2019-07-29 14:22
I'll publish a new preview. @mrbean-bremen if you think the current master is ready for an official release, i'd push an official release soon after.

**Comment by tebjan** [comment] 2019-07-29 14:33
https://www.nuget.org/packages/Svg/3.0.20-g594db9696a

**Comment by mrbean-bremen** [comment] 2019-07-29 16:45
I think an official release would be a good idea. If something pops up after the release, we (e.g. you :) can always make a dot release.

**Comment by gvheertum** [comment] 2019-07-30 08:28
> I think an official release would be a good idea. If something pops up after the release, we (e.g. you :) can always make a dot release.

Agreed, since we move up a major version, I think it's clear to users that there might be compatibility issues. Perhaps for a while we could support the 2.0 versions for legacy purposes and have the 3.0 as current release.

I would expect some might experience/fear issues with the 3.0 since there were quite some changes with regard to the .NET Core migration, so some might prefer staying on the older versions.

**Comment by tebjan** [comment] 2019-07-30 09:34
Yes, sounds good. I'll publish the package today. Thanks for your hard work!

**Comment by mrbean-bremen** [comment] 2019-07-30 10:42
> so some might prefer staying on the older versions.

That's always a possibility - judging by the issues quite a few users do not use the latest nuget version anyway. But having the possibility to use an "official" version that supports .NET is a nice feature.

**Comment by gvheertum** [comment] 2019-08-04 12:41
@tebjan Did you get around to publishing a non-pre-release version of the package? If I look at nuget.org I still see the 3.0 is still flagged as pre-release.

I also thought about adding a small part to the getting started regarding the versions 2 and 3, so I will update the documentation with a proposal.

**Comment by tebjan** [comment] 2019-08-26 10:58
Master branch looks good to me and so far no big issues. I'll publish a 3.0 package.

**Comment by tebjan** [comment] 2019-08-30 22:40
got it, now appveyor will also build the nuget package, including xml documentation: https://www.nuget.org/packages/Svg/

**Closed by tebjan** 2019-08-30 22:40 UTC
Labels: question
