### ISSUE TITLE
Okay for non-interactive use?

### ISSUE THREAD

**Issue by rangercej** [vvvv/SVG#381] opened 2018-12-18 17:10 UTC
Is this code server-safe? Browsing the source, I see it uses System.Drawing, however Microsoft have this huge warning about non-interactive use of this namespace:

> Classes within the System.Drawing namespace are not supported for use within a Windows or ASP.NET service. Attempting to use these classes from within one of these application types may produce unexpected problems, such as diminished service performance and run-time exceptions. For a supported alternative, see Windows Imaging Components.

( https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=netframework-4.7.2 )

I've done some PoC work and it works well for my needs, but the MS warning is currently making me waver.

**Comment by mrbean-bremen** [comment] 2018-12-26 19:04
As the original library has been made for interactive use, and of the known users none seems to use it non-interactively, I'm afraid it is a matter of trying it out.
I guess that the problem is the missing GPU access in service processes, but I don't know which of the drawing functions may be affected by this. Sorry for the non-answer...

**Comment by gvheertum** [comment] 2019-02-21 08:54
I used it in server side code (ASP.NET MVC application and API's) and never had any problems with it. There is however be possible issues regarding use in services and API's, for example the System.Drawing might not always be available in certain situations (if I am not mistaken, some Azure service will not provide the System.Drawing since it relies on GDI calls) and will also be an issue when using it as "portable" code for example in .NET standard or .NET core (but I believe the library is already working on a migration/compatibility with .NET core/standard).

So issues when using System.Drawing are indeed possible when using in a non interactive scenario, since most non-interactive code will often be functioning as service or API, meaning a lot of synchronous calls are possible, which opens a world of possible problems compared to an interactive app which you often only have a few instances loaded. System.Drawing can (and often will) be resource-heavy, so having a lot of synchronous processes will possibly have a huge impact on the performance. So I guess, that is why Microsoft warns about the usage. Rendering a large complex SVG to a big bitmap (eg 5000x5000px) will put a large load on the server, doing this in parallel might cause issues in performance and availability.

System.Drawing was initially not really created for service usage, so you *can* use it, but really need to be aware of possible issues. For example, see this article: https://photosauce.net/blog/post/5-reasons-you-should-stop-using-systemdrawing-from-aspnet

I believe there are some parallelisation tests in the UnitTest suite, since the SVG component did have some concurrency issues in the past. The parallelisation tests show that some parallel work is possible, but upping the limit will show you that resource issues are to be expected under large loads. When failing, System.Drawing will often not fail gracefully, but will often crash with some meaningless error (which makes debugging pretty hard sometimes).

**Comment by mrbean-bremen** [comment] 2019-02-21 17:45
I copied this helpful (IMHO) answer to the [Q&A section](https://github.com/vvvv/SVG/wiki/Q&A#is-this-code-server-safe) - closing.

**Closed by mrbean-bremen** 2019-02-21 17:45 UTC
Labels: question
